# Generated by Django 3.2.8 on 2021-12-17 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gift',
            old_name='isActive',
            new_name='active',
        ),
    ]
