# Generated by Django 3.2.8 on 2021-12-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0002_rename_isactive_gift_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
