# Generated by Django 3.2.8 on 2021-12-17 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0003_gift_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gift',
            old_name='desciption',
            new_name='description',
        ),
    ]
