# Generated by Django 3.2.8 on 2021-12-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0004_rename_desciption_gift_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
